
USE java25_shopping;
SET @OLD_SQL_SAFE_UPDATES = @@SQL_SAFE_UPDATES;
SET SQL_SAFE_UPDATES = 0;

-- 1. Tạo dữ liệu kiểm thử cho bảng T07_BILL
SET @HAS_C07_DELIVERY_FEE = (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'T07_BILL'
      AND COLUMN_NAME = 'C07_DELIVERY_FEE'
);

SET @SQL_FIX_FEE = IF(
    @HAS_C07_DELIVERY_FEE = 0,
    'ALTER TABLE T07_BILL ADD COLUMN C07_DELIVERY_FEE INT NOT NULL DEFAULT 0 AFTER C07_ORDER_ID',
    'SELECT ''C07_DELIVERY_FEE da ton tai'' AS THONG_BAO'
);
PREPARE STMT_FIX_FEE FROM @SQL_FIX_FEE;
EXECUTE STMT_FIX_FEE;
DEALLOCATE PREPARE STMT_FIX_FEE;

SET @HAS_TOTAL_OF_MONEY = (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'T07_BILL'
      AND COLUMN_NAME = 'C10_TOTAL_OF_MONEY'
);

SET @SQL_FIX_TOTAL = IF(
    @HAS_TOTAL_OF_MONEY = 0,
    'ALTER TABLE T07_BILL ADD COLUMN C10_TOTAL_OF_MONEY DECIMAL(17,2) NOT NULL DEFAULT 0 AFTER C07_DELIVERY_FEE',
    'SELECT ''C10_TOTAL_OF_MONEY da ton tai'' AS THONG_BAO'
);
PREPARE STMT_FIX_TOTAL FROM @SQL_FIX_TOTAL;
EXECUTE STMT_FIX_TOTAL;
DEALLOCATE PREPARE STMT_FIX_TOTAL;

TRUNCATE TABLE T07_BILL;

INSERT INTO T07_BILL (
    C07_ORDER_ID,
    C07_DELIVERY_FEE,
    C10_TOTAL_OF_MONEY
)
SELECT o.C06_ORDER_ID,
       CASE FLOOR(RAND() * 4)
           WHEN 0 THEN 20
           WHEN 1 THEN 30
           WHEN 2 THEN 40
           ELSE 50
       END AS C07_DELIVERY_FEE,
       0 AS C10_TOTAL_OF_MONEY
FROM T06_ORDER o
WHERE o.C06_ORDER_ID NOT IN (11, 12)
ORDER BY o.C06_ORDER_ID;

SELECT C07_BILL_ID,
       C07_ORDER_ID,
       C07_DELIVERY_FEE,
       C10_TOTAL_OF_MONEY
FROM T07_BILL
ORDER BY C07_ORDER_ID;


-- 2. Tạo dữ liệu kiểm thử cho bảng T17_ORDER_STATUS_DETAIL

TRUNCATE TABLE T17_ORDER_STATUS_DETAIL;

INSERT INTO T17_ORDER_STATUS_DETAIL (
    C17_ORDER_ID,
    C17_ORDER_STATUS_ID,
    C17_EMPLOYEE_ID,
    C17_LAST_UPDATED
)
SELECT x.ORDER_ID,
       x.STATUS_ID,
       x.EMPLOYEE_ID,
       DATE_SUB(SYSDATE(), INTERVAL (x.MAX_STATUS_ID - x.STATUS_ID) DAY) AS LAST_UPDATED
FROM (
    SELECT o.C06_ORDER_ID AS ORDER_ID,
           s.STATUS_ID,
           CASE
               WHEN o.C06_ORDER_ID BETWEEN 1 AND 5 THEN 1
               WHEN o.C06_ORDER_ID BETWEEN 6 AND 8 THEN 2
               WHEN o.C06_ORDER_ID BETWEEN 9 AND 10 THEN 3
               WHEN o.C06_ORDER_ID BETWEEN 11 AND 12 THEN 4
               WHEN o.C06_ORDER_ID = 13 THEN 5
           END AS EMPLOYEE_ID,
           CASE
               WHEN o.C06_ORDER_ID BETWEEN 1 AND 5 THEN 5
               WHEN o.C06_ORDER_ID BETWEEN 6 AND 8 THEN 3
               WHEN o.C06_ORDER_ID BETWEEN 9 AND 10 THEN 4
               WHEN o.C06_ORDER_ID BETWEEN 11 AND 12 THEN 7
               WHEN o.C06_ORDER_ID = 13 THEN 6
           END AS MAX_STATUS_ID
    FROM T06_ORDER o
    JOIN (
        SELECT 1 AS STATUS_ID
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
    ) s
      ON (o.C06_ORDER_ID BETWEEN 1 AND 5  AND s.STATUS_ID BETWEEN 1 AND 5)
      OR (o.C06_ORDER_ID BETWEEN 6 AND 8  AND s.STATUS_ID BETWEEN 1 AND 3)
      OR (o.C06_ORDER_ID BETWEEN 9 AND 10 AND s.STATUS_ID BETWEEN 1 AND 4)
      OR (o.C06_ORDER_ID BETWEEN 11 AND 12 AND s.STATUS_ID = 7)
      OR (o.C06_ORDER_ID = 13 AND s.STATUS_ID IN (1, 2, 3, 4, 6))
    WHERE o.C06_ORDER_ID BETWEEN 1 AND 13
) x
ORDER BY x.ORDER_ID, x.STATUS_ID;

SELECT *
FROM T17_ORDER_STATUS_DETAIL
ORDER BY C17_ORDER_ID, C17_ORDER_STATUS_ID;

-- 3. Liệt kê toàn bộ thông tin các loại hàng
SELECT *
FROM T02_ITEM_GROUP;


-- 4. Liệt kê các mặt hàng thuộc loại hàng là >__$$__<
SET @MA_LOAI = 1;

SELECT i.*
FROM T01_ITEM i
LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
WHERE COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) = @MA_LOAI;


-- 5. Liệt kê top 5 mặt hàng có giá bán cao nhất
SELECT i.C01_ITEM_ID,
       i.C01_ITEM_NAME,
       d.C14_ITEM_DETAIL_ID,
       d.C14_SIZE_ID,
       d.C14_SALES_PRICE
FROM T01_ITEM i
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
ORDER BY d.C14_SALES_PRICE DESC, i.C01_ITEM_ID ASC
LIMIT 5;


-- 6. Liệt kê toàn bộ đơn hàng
SELECT *
FROM T06_ORDER
ORDER BY C06_ORDER_ID;


-- 7. Liệt kê các đơn hàng được bán trong ngày >__$$__<
SET @NGAY_BAN = '2026-04-18';

SELECT *
FROM T06_ORDER
WHERE DATE(C06_ORDER_DATE) = @NGAY_BAN
ORDER BY C06_ORDER_DATE;


-- 8. Liệt kê các đơn hàng được bán từ ngày >__$$1__< đến ngày >__$$2__<
SET @TU_NGAY = '2026-04-12';
SET @DEN_NGAY = '2026-04-18';

SELECT *
FROM T06_ORDER
WHERE C06_ORDER_DATE >= @TU_NGAY
  AND C06_ORDER_DATE < DATE_ADD(@DEN_NGAY, INTERVAL 1 DAY)
ORDER BY C06_ORDER_DATE;


-- 9. Liệt kê các đơn hàng được bán trong tháng __mm/yyyy__
SET @THANG = 4;
SET @NAM = 2026;

SELECT *
FROM T06_ORDER
WHERE MONTH(C06_ORDER_DATE) = @THANG
  AND YEAR(C06_ORDER_DATE) = @NAM
ORDER BY C06_ORDER_DATE;


-- 10. Liệt kê các đơn hàng được giao tại >__$$__<
SET @DIA_CHI_GIAO = 'Địa chỉ 1';

SELECT *
FROM T06_ORDER
WHERE C06_DELIVERY_ADDRESS LIKE CONCAT('%', @DIA_CHI_GIAO, '%')
ORDER BY C06_ORDER_ID;


-- 11. Giá của toàn bộ các mặt hàng sau khi được khuyến mãi >__$$__<, làm tròn 2 chữ số thập phân
SET @KHUYEN_MAI = 10;

SELECT i.C01_ITEM_ID,
       i.C01_ITEM_NAME,
       d.C14_ITEM_DETAIL_ID,
       d.C14_SALES_PRICE AS GIA_BAN_GOC,
       ROUND(d.C14_SALES_PRICE * (100 - @KHUYEN_MAI) / 100, 2) AS GIA_SAU_KHUYEN_MAI
FROM T01_ITEM i
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
ORDER BY i.C01_ITEM_ID, d.C14_ITEM_DETAIL_ID;


-- 12. Giảm giá >__$$__< tất cả các mặt hàng trong ngày >__dd/mm/yyyy__<
SET @PHAN_TRAM_GIAM = 10;
SET @NGAY_GIAM_GIA = '2026-04-18';

UPDATE T14_ITEM_DETAIL d
JOIN (
    SELECT DISTINCT od.C16_ITEM_DETAIL_ID
    FROM T16_ORDER_DETAIL od
    JOIN T06_ORDER o ON o.C06_ORDER_ID = od.C16_ORDER_ID
    WHERE DATE(o.C06_ORDER_DATE) = @NGAY_GIAM_GIA
) x ON x.C16_ITEM_DETAIL_ID = d.C14_ITEM_DETAIL_ID
SET d.C14_SALES_PRICE = ROUND(d.C14_SALES_PRICE * (100 - @PHAN_TRAM_GIAM) / 100, 2);

SELECT DISTINCT i.C01_ITEM_ID,
       i.C01_ITEM_NAME,
       d.C14_ITEM_DETAIL_ID,
       d.C14_SALES_PRICE
FROM T06_ORDER o
JOIN T16_ORDER_DETAIL od ON od.C16_ORDER_ID = o.C06_ORDER_ID
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_DETAIL_ID = od.C16_ITEM_DETAIL_ID
JOIN T01_ITEM i ON i.C01_ITEM_ID = d.C14_ITEM_ID
WHERE DATE(o.C06_ORDER_DATE) = @NGAY_GIAM_GIA
ORDER BY i.C01_ITEM_ID;


-- 13. Liệt kê tất cả các màu sắc của sản phẩm có bán trong cửa hàng.
SELECT DISTINCT C01_COLOR
FROM T01_ITEM
WHERE C01_COLOR IS NOT NULL
ORDER BY C01_COLOR;


-- 14. Liệt kê thông tin các mặt hàng (MaMH, TenMH, ThoiGianDatHang) được bán trong ngày >__dd/mm/yyyy__<
SET @NGAY_CAU_14 = '2026-04-18';

SELECT DISTINCT i.C01_ITEM_ID AS MaMH,
       i.C01_ITEM_NAME AS TenMH,
       o.C06_ORDER_DATE AS ThoiGianDatHang
FROM T06_ORDER o
JOIN T16_ORDER_DETAIL od ON od.C16_ORDER_ID = o.C06_ORDER_ID
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_DETAIL_ID = od.C16_ITEM_DETAIL_ID
JOIN T01_ITEM i ON i.C01_ITEM_ID = d.C14_ITEM_ID
WHERE DATE(o.C06_ORDER_DATE) = @NGAY_CAU_14
ORDER BY o.C06_ORDER_DATE, i.C01_ITEM_ID;


-- 15. Liệt kê các mặt hàng có giá bán từ >__$$1__< đến >__$$2__<
SET @GIA_TU = 200;
SET @GIA_DEN = 600;

SELECT i.C01_ITEM_ID,
       i.C01_ITEM_NAME,
       d.C14_ITEM_DETAIL_ID,
       d.C14_SALES_PRICE
FROM T01_ITEM i
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
WHERE d.C14_SALES_PRICE BETWEEN @GIA_TU AND @GIA_DEN
ORDER BY d.C14_SALES_PRICE;


-- 16. Liệt kê tất cả các mặt hàng thuộc loại hàng là >__$$1__< và >__$$2__<
SET @MA_LOAI_1 = 1;
SET @MA_LOAI_2 = 2;

SELECT i.*
FROM T01_ITEM i
LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
WHERE COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) IN (@MA_LOAI_1, @MA_LOAI_2)
ORDER BY COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID), i.C01_ITEM_ID;


-- 17. Liệt kê các đơn hàng được đặt trong ngày (>__$$1__<, >__$$2__<)
SET @THOI_GIAN_TU = '2026-04-18 00:00:00';
SET @THOI_GIAN_DEN = '2026-04-18 23:59:59';

SELECT *
FROM T06_ORDER
WHERE C06_ORDER_DATE BETWEEN @THOI_GIAN_TU AND @THOI_GIAN_DEN
ORDER BY C06_ORDER_DATE;


-- 18. Sắp xếp các mặt hàng với giá bán tăng dần
SELECT i.C01_ITEM_ID,
       i.C01_ITEM_NAME,
       d.C14_ITEM_DETAIL_ID,
       d.C14_SALES_PRICE
FROM T01_ITEM i
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
ORDER BY d.C14_SALES_PRICE ASC;


-- 19. Sắp xếp các mặt hàng với giá mua giảm dần
SELECT *
FROM T01_ITEM
ORDER BY C01_BUY_PRICE DESC;


-- 20. Sắp xếp các mặt hàng với giá bán tăng dần, giá mua giảm dần
SELECT i.C01_ITEM_ID,
       i.C01_ITEM_NAME,
       i.C01_BUY_PRICE,
       d.C14_ITEM_DETAIL_ID,
       d.C14_SALES_PRICE
FROM T01_ITEM i
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
ORDER BY d.C14_SALES_PRICE ASC, i.C01_BUY_PRICE DESC;


-- 21. Đếm số lượng các mặt hàng trong hệ thống
SELECT COUNT(*) AS SO_LUONG_MAT_HANG
FROM T01_ITEM;


-- 22. Số lượng 'Giày da Nam' được bán trong ngày >__$$__<
SET @NGAY_CAU_22 = '2026-04-18';

SELECT COALESCE(SUM(od.C16_AMOUNT), 0) AS SO_LUONG_GIAY_DA_NAM_DA_BAN
FROM T06_ORDER o
JOIN T16_ORDER_DETAIL od ON od.C16_ORDER_ID = o.C06_ORDER_ID
JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_DETAIL_ID = od.C16_ITEM_DETAIL_ID
JOIN T01_ITEM i ON i.C01_ITEM_ID = d.C14_ITEM_ID
WHERE i.C01_ITEM_NAME = 'Giày da Nam'
  AND DATE(o.C06_ORDER_DATE) = @NGAY_CAU_22;


-- 23. Đếm số lượng các mặt hàng theo từng loại hàng
WITH ITEM_WITH_GROUP AS (
    SELECT i.C01_ITEM_ID,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       COUNT(i.C01_ITEM_ID) AS SO_LUONG_MAT_HANG
FROM T02_ITEM_GROUP g
LEFT JOIN ITEM_WITH_GROUP i ON i.ITEM_GROUP_ID = g.C02_ITEM_GROUP_ID
GROUP BY g.C02_ITEM_GROUP_ID, g.C02_ITEM_GROUP_NAME
ORDER BY g.C02_ITEM_GROUP_ID;


-- 24. Tìm mặt hàng có giá bán cao nhất trong loại hàng >__$$__<
SET @MA_LOAI_CAU_24 = 1;

WITH ITEM_PRICE AS (
    SELECT i.C01_ITEM_ID,
           i.C01_ITEM_NAME,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID,
           MAX(d.C14_SALES_PRICE) AS GIA_BAN
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
    JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
    WHERE COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) = @MA_LOAI_CAU_24
    GROUP BY i.C01_ITEM_ID,
             i.C01_ITEM_NAME,
             COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID)
)
SELECT *
FROM ITEM_PRICE
WHERE GIA_BAN = (SELECT MAX(GIA_BAN) FROM ITEM_PRICE);


-- 25. Tìm mặt hàng có giá bán cao nhất của mỗi loại hàng
WITH ITEM_PRICE AS (
    SELECT i.C01_ITEM_ID,
           i.C01_ITEM_NAME,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID,
           MAX(d.C14_SALES_PRICE) AS GIA_BAN
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
    JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
    GROUP BY i.C01_ITEM_ID,
             i.C01_ITEM_NAME,
             COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID)
), XEP_HANG AS (
    SELECT p.*,
           DENSE_RANK() OVER (
               PARTITION BY p.ITEM_GROUP_ID
               ORDER BY p.GIA_BAN DESC
           ) AS RNK
    FROM ITEM_PRICE p
    WHERE p.ITEM_GROUP_ID IS NOT NULL
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       x.C01_ITEM_ID,
       x.C01_ITEM_NAME,
       x.GIA_BAN
FROM XEP_HANG x
JOIN T02_ITEM_GROUP g ON g.C02_ITEM_GROUP_ID = x.ITEM_GROUP_ID
WHERE x.RNK = 1
ORDER BY g.C02_ITEM_GROUP_ID, x.C01_ITEM_ID;


-- 26. Tìm tổng số lượng mặt hàng của mỗi loại hàng trong hệ thống
WITH ITEM_WITH_GROUP AS (
    SELECT i.C01_ITEM_ID,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       COALESCE(SUM(d.C14_AMOUNT), 0) AS TONG_SO_LUONG
FROM T02_ITEM_GROUP g
LEFT JOIN ITEM_WITH_GROUP i ON i.ITEM_GROUP_ID = g.C02_ITEM_GROUP_ID
LEFT JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
GROUP BY g.C02_ITEM_GROUP_ID, g.C02_ITEM_GROUP_NAME
ORDER BY g.C02_ITEM_GROUP_ID;


-- 27. Hiển thị tổng số lượng mặt hàng của mỗi loại hàng trong hệ thống,
SET @SO_LUONG_TOI_THIEU = 500;

WITH ITEM_WITH_GROUP AS (
    SELECT i.C01_ITEM_ID,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       COALESCE(SUM(d.C14_AMOUNT), 0) AS TONG_SO_LUONG
FROM T02_ITEM_GROUP g
LEFT JOIN ITEM_WITH_GROUP i ON i.ITEM_GROUP_ID = g.C02_ITEM_GROUP_ID
LEFT JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
GROUP BY g.C02_ITEM_GROUP_ID, g.C02_ITEM_GROUP_NAME
HAVING COALESCE(SUM(d.C14_AMOUNT), 0) > @SO_LUONG_TOI_THIEU
ORDER BY TONG_SO_LUONG DESC;


-- 28. Hiển thị mặt hàng có số lượng nhiều nhất trong mỗi loại hàng
WITH ITEM_STOCK AS (
    SELECT i.C01_ITEM_ID,
           i.C01_ITEM_NAME,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID,
           COALESCE(SUM(d.C14_AMOUNT), 0) AS SO_LUONG
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
    LEFT JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
    GROUP BY i.C01_ITEM_ID,
             i.C01_ITEM_NAME,
             COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID)
), XEP_HANG AS (
    SELECT s.*,
           DENSE_RANK() OVER (
               PARTITION BY s.ITEM_GROUP_ID
               ORDER BY s.SO_LUONG DESC
           ) AS RNK
    FROM ITEM_STOCK s
    WHERE s.ITEM_GROUP_ID IS NOT NULL
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       x.C01_ITEM_ID,
       x.C01_ITEM_NAME,
       x.SO_LUONG
FROM XEP_HANG x
JOIN T02_ITEM_GROUP g ON g.C02_ITEM_GROUP_ID = x.ITEM_GROUP_ID
WHERE x.RNK = 1
ORDER BY g.C02_ITEM_GROUP_ID, x.C01_ITEM_ID;


-- 29. Hiển thị giá bán trung bình của mỗi loại hàng
WITH ITEM_WITH_GROUP AS (
    SELECT i.C01_ITEM_ID,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       ROUND(AVG(d.C14_SALES_PRICE), 2) AS GIA_BAN_TRUNG_BINH
FROM T02_ITEM_GROUP g
LEFT JOIN ITEM_WITH_GROUP i ON i.ITEM_GROUP_ID = g.C02_ITEM_GROUP_ID
LEFT JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
GROUP BY g.C02_ITEM_GROUP_ID, g.C02_ITEM_GROUP_NAME
ORDER BY g.C02_ITEM_GROUP_ID;


-- 30. In ra 3 loại hàng có số lượng hàng còn lại nhiều nhất ở thời điểm hiện tại
WITH ITEM_WITH_GROUP AS (
    SELECT i.C01_ITEM_ID,
           COALESCE(i.C01_ITEM_GROUP_ID, sg.C03_ITEM_GROUP_ID) AS ITEM_GROUP_ID
    FROM T01_ITEM i
    LEFT JOIN T03_SUB_ITEM_GROUP sg ON sg.C03_SIG_ID = i.C01_SIG_ID
)
SELECT g.C02_ITEM_GROUP_ID,
       g.C02_ITEM_GROUP_NAME,
       COALESCE(SUM(d.C14_AMOUNT), 0) AS SO_LUONG_CON_LAI
FROM T02_ITEM_GROUP g
LEFT JOIN ITEM_WITH_GROUP i ON i.ITEM_GROUP_ID = g.C02_ITEM_GROUP_ID
LEFT JOIN T14_ITEM_DETAIL d ON d.C14_ITEM_ID = i.C01_ITEM_ID
GROUP BY g.C02_ITEM_GROUP_ID, g.C02_ITEM_GROUP_NAME
ORDER BY SO_LUONG_CON_LAI DESC
LIMIT 3;