-- Tạo bảng liên quan đến enumeration

-- AUTO_INCREMENT khi thêm dữ liệu, nếu không truyền dữ liệu cho column, thì tự động lấy giá trị lớn nhất
-- của column đó +1 (chỉ reset biến trong service khi dùng lệnh TRUNCATE)

-- HQT khác dùng SEQUENCE tự khai báo bước nhảy

-- T90_PAYMENT_METHOD
DROP TABLE IF EXISTS T90_PAYMENT_METHOD;
CREATE TABLE IF NOT EXISTS T90_PAYMENT_METHOD (
	C90_PAYMENT_METHOD_ID INT PRIMARY KEY AUTO_INCREMENT,
	C90_PAYMENT_METHOD_NAME VARCHAR(255) NOT NULL
);

-- T91_ORDER_STATUS
DROP TABLE IF EXISTS T91_ORDER_STATUS;
CREATE TABLE IF NOT EXISTS T91_ORDER_STATUS (
	C91_ORDER_STATUS_ID INT AUTO_INCREMENT,
	C91_ORDER_STATUS_DESC VARCHAR(255) NOT NULL,
    PRIMARY KEY (C91_ORDER_STATUS_ID)
);
