-- Tạo bảng liên quan đến người dùng(khách hàng, nhân viên)

-- T08_CUSTOMER
DROP TABLE IF EXISTS T08_CUSTOMER;
CREATE TABLE IF NOT EXISTS T08_CUSTOMER (
	C08_CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
	C08_CUSTOMER_NAME VARCHAR(255) NOT NULL,
    C08_CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    C08_CUSTOMER_PHONE VARCHAR(50) NOT NULL,
    C08_CUSTOMER_ADDRESS TEXT,
    C08_CUSTOMER_PASSWORD TEXT NOT NULL,
    C08_SOCIAL_MEDIA VARCHAR(255) NOT NULL,
    C08_SM_TOKEN VARCHAR(255) NOT NULL,
    CONSTRAINT UNQ_CUSTOMER_EMAIL UNIQUE(C08_CUSTOMER_EMAIL),
    CONSTRAINT UNQ_CUSTOMER_PHONE UNIQUE(C08_CUSTOMER_PHONE)
);

-- T09_EMPLOYEE
DROP TABLE IF EXISTS T09_EMPLOYEE;
CREATE TABLE IF NOT EXISTS T09_EMPLOYEE (
	C09_EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
	C09_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
    C09_EMPLOYEE_EMAIL VARCHAR(255) NOT NULL,
    C09_EMPLOYEE_PHONE VARCHAR(50) NOT NULL,
    CONSTRAINT UNQ_EMPLOYEE_EMAIL UNIQUE(C09_EMPLOYEE_EMAIL),
    CONSTRAINT UNQ_EMPLOYEE_PHONE UNIQUE(C09_EMPLOYEE_PHONE)
)