-- Tạo bảng liên quan đến loại hàng

-- T02_ITEM_GROUP
DROP TABLE IF EXISTS T02_ITEM_GROUP;
CREATE TABLE IF NOT EXISTS T02_ITEM_GROUP (
	C02_ITEM_GROUP_ID INT PRIMARY KEY AUTO_INCREMENT,
	C02_ITEM_GROUP_NAME VARCHAR(255) NOT NULL,
    C02_STATUS BIT NOT NULL DEFAULT(0)
);

ALTER TABLE T02_ITEM_GROUP ADD
CONSTRAINT UNQ_ITEM_GROUP_NAME UNIQUE(C02_ITEM_GROUP_NAME);

-- T03_SUB_ITEM_GROUP
DROP TABLE IF EXISTS T03_SUB_ITEM_GROUP;
CREATE TABLE IF NOT EXISTS T03_SUB_ITEM_GROUP (
	C03_SIG_ID INT PRIMARY KEY AUTO_INCREMENT,
	C03_SIG_NAME VARCHAR(255) NOT NULL,
    C03_ITEM_GROUP_ID INT NOT NULL,
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_ITEM_GROUP_ID) REFERENCES T02_ITEM_GROUP(C02_ITEM_GROUP_ID)
);

ALTER TABLE T03_SUB_ITEM_GROUP ADD
CONSTRAINT UNQ_SIG_NAME UNIQUE(C03_SIG_NAME);