-- Tạo bảng liên quan đến mặt hàng, hình ảnh

-- T01_ITEM
DROP TABLE IF EXISTS T01_ITEM;
CREATE TABLE IF NOT EXISTS T01_ITEM (
	C01_ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
	C01_ITEM_NAME VARCHAR(255) NOT NULL,
    C01_BUY_PRICE DECIMAL(17, 2) NOT NULL,
    C01_MATERIAL VARCHAR(255) NOT NULL,
    C01_COLOR VARCHAR(50),
    C01_SIG_ID INT,
    C01_ITEM_GROUP_ID INT,
    CONSTRAINT FK_T01_T03 FOREIGN KEY (C01_SIG_ID) REFERENCES T03_SUB_ITEM_GROUP(C03_SIG_ID),
    CONSTRAINT FK_T01_T02 FOREIGN KEY (C01_ITEM_GROUP_ID) REFERENCES T02_ITEM_GROUP(C02_ITEM_GROUP_ID)
);

-- T10_GALLERY
DROP TABLE IF EXISTS T10_GALLERY;
CREATE TABLE IF NOT EXISTS T10_GALLERY (
	C10_ITEM_ID INT NOT NULL,
	C10_IMAGE_PATH VARCHAR(255) NOT NULL,
    CONSTRAINT PRIMARY KEY (C10_ITEM_ID, C10_IMAGE_PATH),
    CONSTRAINT FK_T10_T01 FOREIGN KEY (C10_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);