-- Tạo bảng liên quan đến chi tiết mặt hàng

-- T04_SIZE
DROP TABLE IF EXISTS T04_SIZE;
CREATE TABLE IF NOT EXISTS T04_SIZE (
	C04_SIZE_ID INT PRIMARY KEY AUTO_INCREMENT,
	C04_SIZE_NAME VARCHAR(50) NOT NULL,
    C04_GENDER BIT NOT NULL DEFAULT(0),
    C04_SIZE_DESC TEXT NOT NULL,
    CONSTRAINT UNQ_SIZE_NAME_GENDER UNIQUE(C04_SIZE_NAME, C04_GENDER),
    CONSTRAINT CHK_SIZE_NAME CHECK (C04_SIZE_NAME IN ('S', 'XS', 'M', 'L', 'XL', 'XXL'))
);

-- T14_ITEM_DETAIL
DROP TABLE IF EXISTS T14_ITEM_DETAIL;
CREATE TABLE IF NOT EXISTS T14_ITEM_DETAIL (
	C14_ITEM_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
    C14_ITEM_ID INT NOT NULL,
    C14_SIZE_ID INT NOT NULL,
    C14_SALES_PRICE DECIMAL(17, 2) NOT NULL,
    C14_AMOUNT INT NOT NULL,
    CONSTRAINT UNQ_ITEM_SIZE UNIQUE(C14_ITEM_ID, C14_SIZE_ID),
    CONSTRAINT FK_T14_01 FOREIGN KEY (C14_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
    CONSTRAINT FK_T14_03 FOREIGN KEY (C14_SIZE_ID) REFERENCES T04_SIZE(C04_SIZE_ID)
);

-- T05_PROVIDER
DROP TABLE IF EXISTS T05_PROVIDER;
CREATE TABLE IF NOT EXISTS T05_PROVIDER (
	C05_PROVIDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C05_PROVIDER_NAME VARCHAR(255) NOT NULL,
    C05_PROVIDER_TAX_PCT INT NOT NULL,
    CONSTRAINT UNQ_PROVIDER_NAME UNIQUE(C05_PROVIDER_NAME)
);

-- T15_ITEM_RECEIPT_DETAIL
DROP TABLE IF EXISTS T15_ITEM_RECEIPT_DETAIL;
CREATE TABLE IF NOT EXISTS T15_ITEM_RECEIPT_DETAIL (
	C15_PROVIDER_ID INT NOT NULL,
	C15_ITEM_ID INT NOT NULL,
    C15_BUY_PRICE DECIMAL(17, 2) NOT NULL,
    C15_AMOUNT INT NOT NULL,
	C15_RECEIPT_DATE DATE NOT NULL DEFAULT(current_timestamp()),
    CONSTRAINT PRIMARY KEY (C15_PROVIDER_ID, C15_ITEM_ID),
    CONSTRAINT FK_T15_T05 FOREIGN KEY (C15_PROVIDER_ID) REFERENCES T05_PROVIDER(C05_PROVIDER_ID),
    CONSTRAINT FK_T15_T01 FOREIGN KEY (C15_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);