-- Tạo bảng liên quan đến đơn hàng, hóa đơn

-- T06_ORDER
DROP TABLE IF EXISTS T06_ORDER;
CREATE TABLE IF NOT EXISTS T06_ORDER (
	C06_ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
	C06_DELIVERY_ADDRESS TEXT NOT NULL,
	C06_DELIVERY_FEE INT,
	C06_RECEIVER_PHONE VARCHAR(50) NOT NULL,
	C06_ORDER_DATE DATETIME NOT NULL DEFAULT(current_timestamp()),
	C06_EXPECTED_DELIVERY_DATE DATE,
	C06_PAYMENT_METHOD_ID INT NOT NULL,
	C06_CUSTOMER_ID INT NOT NULL,
    CONSTRAINT FK_T06_T09 FOREIGN KEY (C06_PAYMENT_METHOD_ID) REFERENCES T90_PAYMENT_METHOD(C90_PAYMENT_METHOD_ID),
    CONSTRAINT FK_T06_T08 FOREIGN KEY (C06_CUSTOMER_ID) REFERENCES T08_CUSTOMER(C08_CUSTOMER_ID)
);

-- T07_BILL
DROP TABLE IF EXISTS T07_BILL;
CREATE TABLE IF NOT EXISTS T07_BILL (
	C07_BILL_ID INT PRIMARY KEY AUTO_INCREMENT,
    C07_ORDER_ID INT NOT NULL,
    C07_TOTAL_OF_MONEY DECIMAL(17, 2) NOT NULL DEFAULT(0),
    CONSTRAINT FK_T07_T06 FOREIGN KEY (C07_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID)
);

-- Relationship 1-1
ALTER TABLE T07_BILL ADD
CONSTRAINT UNQ_ORDER_ID UNIQUE(C07_ORDER_ID);
