-- Tạo bảng liên quan đến đơn hàng, hóa đơn
-- T06_ORDER
DROP TABLE IF EXISTS T07_BILL; -- Phải drop bảng T07 trước vì T07 tham chiếu khóa ngoại tới T06
DROP TABLE IF EXISTS T06_ORDER;

CREATE TABLE IF NOT EXISTS T06_ORDER (
    C06_ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C06_DELIVERY_ADDRESS TEXT NOT NULL,
    C06_DELIVERY_FEE INT,
    C06_RECEIVER_PHONE VARCHAR(50) NOT NULL,
    C06_ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    C06_EXPECTED_DELIVERY_DATE DATE,
    C06_PAYMENT_METHOD_ID INT NOT NULL,
    C06_CUSTOMER_ID INT NOT NULL,
    C06_EMPLOYEE_ID INT, -- Đã bổ sung cột này
    CONSTRAINT FK_T06_T90 FOREIGN KEY (C06_PAYMENT_METHOD_ID) REFERENCES T90_PAYMENT_METHOD(C90_PAYMENT_METHOD_ID),
    CONSTRAINT FK_T06_T08 FOREIGN KEY (C06_CUSTOMER_ID) REFERENCES T08_CUSTOMER(C08_CUSTOMER_ID)
    -- Nếu có bảng T05_EMPLOYEE thì có thể mở comment dòng dưới để tạo FK:
    -- , CONSTRAINT FK_T06_T05 FOREIGN KEY (C06_EMPLOYEE_ID) REFERENCES T05_EMPLOYEE(C05_EMPLOYEE_ID)
);

-- T07_BILL
CREATE TABLE IF NOT EXISTS T07_BILL (
    C07_BILL_ID INT PRIMARY KEY AUTO_INCREMENT,
    C07_ORDER_ID INT NOT NULL UNIQUE, -- Đưa UNIQUE trực tiếp vào đây cho gọn thay vì dùng ALTER TABLE
    C07_TOTAL_OF_MONEY DECIMAL(17, 2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_T07_T06 FOREIGN KEY (C07_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID)
);

-- Relationship 1-1
ALTER TABLE T07_BILL ADD
CONSTRAINT UNQ_ORDER_ID UNIQUE(C07_ORDER_ID);
