-- Tạo bảng liên quan đến chi tiết đơn hàng

-- T16_ORDER_DETAIL
DROP TABLE IF EXISTS T16_ORDER_DETAIL;
CREATE TABLE IF NOT EXISTS T16_ORDER_DETAIL (
	C16_ORDER_ID INT NOT NULL,
	C16_ITEM_DETAIL_ID INT NOT NULL,
	C16_AMOUNT INT NOT NULL,
	CONSTRAINT PRIMARY KEY (C16_ORDER_ID, C16_ITEM_DETAIL_ID),
    CONSTRAINT FK_T16_T06 FOREIGN KEY (C16_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID),
    CONSTRAINT FK_T16_T14 FOREIGN KEY (C16_ITEM_DETAIL_ID) REFERENCES T14_ITEM_DETAIL(C14_ITEM_DETAIL_ID)
);	

-- T17_ORDER_STATUS_DETAIL
DROP TABLE IF EXISTS T17_ORDER_STATUS_DETAIL;
CREATE TABLE IF NOT EXISTS T17_ORDER_STATUS_DETAIL (
	C17_ORDER_ID INT NOT NULL,
	C17_ORDER_STATUS_ID INT NOT NULL,
	C17_EMPLOYEE_ID INT NOT NULL,
	C17_LAST_UPDATED DATETIME NOT NULL DEFAULT(current_timestamp()),
    CONSTRAINT PRIMARY KEY (C17_ORDER_ID, C17_ORDER_STATUS_ID),
    CONSTRAINT FK_T17_T06 FOREIGN KEY (C17_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID),
    CONSTRAINT FK_T17_T91 FOREIGN KEY (C17_ORDER_STATUS_ID) REFERENCES T91_ORDER_STATUS(C91_ORDER_STATUS_ID),
    CONSTRAINT FK_T17_T09 FOREIGN KEY (C17_EMPLOYEE_ID) REFERENCES T09_EMPLOYEE(C09_EMPLOYEE_ID)
);