-- Một số cập nhật khi tạo test_data

-- T06_ORDER
ALTER TABLE T06_ORDER DROP COLUMN C06_DELIVERY_FEE;
ALTER TABLE T06_ORDER ADD C06_EMPLOYEE_ID INT NOT NULL;

-- T07_BILL
ALTER TABLE T07_BILL ADD C07_DELIVERY_FEE INT;